### ISSUE TITLE
CSVDetectionReader not parsing csv successfully

### ISSUE THREAD

**Issue by Jack2104** [dstl/Stone-Soup#1030]
I'm trying to parse some data with the CSV Reader, and I'm having some issues. I'm using it like so: `detection_reader = CSVDetectionReader(detections_csv_fp, state_vector_fields=("delay", "doppler"), time_field="timestamp", timestamp=True)` and I'm getting the following value in `detection_reader.detections`: "AttributeError("'CSVDetectionReader' object has no attribute 'current'")".

Here's a snippet of my csv file:
```
delay,doppler,timestamp
7.95,87.81,1713883987987
22.47,195.47,1713883987987
35.93,-95.29,1713883989845
```

Any idea what could be going wrong? I'm new to stone soup and trying to find my way around it

**Comment by apiszcz** [comment]
fysa

https://github.com/dstl/Stone-Soup/issues/971

**Comment by sdhiscocks** [comment]
@Jack2104 The issue is that with the readers, they are designed to iterated over and they yield the data. It's designed this way so when you have sources of data that can't be read at once, for example a real camera.

this should work:

```python
detection_reader = CSVDetectionReader(detections_csv_fp, state_vector_fields=("delay", "doppler"), time_field="timestamp", timestamp=True)

all_time_detections = set()
for time, current_detections in detection_reader:
    print(time, detections)
    all_time_detections |= current_detections 
```

**Comment by Jack2104** [comment]
Thanks! Sorry for re-opening this after so long, I had my university exam period. I've tried doing as you said, with the `for time, currrent_detections in detection_reader`, however I get the error:

> OSError: [Errno 22] Invalid argument

However nothing seems amiss when inspecting the internals of the `detection_reader` with my debugger. Any guidance as to what might be happening?
