### ISSUE TITLE
Low efficiency in GOSPA metric computations

### ISSUE THREAD

**Issue by narykov** [dstl/Stone-Soup#1032]
I'm using [the GOSPA metric](https://stonesoup.readthedocs.io/en/latest/stonesoup.metricgenerator.ospametric.html#stonesoup.metricgenerator.ospametric.GOSPAMetric) to evaluate the tracking results in a scenario that has generated 40 tracks over 30,000 time steps, and I've been waiting for results for more than a couple of hours. I understand that this isn't a trivial scenario, but it made me think about how efficient is the metric's implementation. 

The description indicates that the metric relies on the auction algorithm, which may not be the fastest option here. Angel Garcia-Fernandez [provides](https://github.com/Agarciafernandez/MTT/blob/master/GOSPA%20code/GOSPA.m) an improved (MATLAB) implementation that uses the [`assign2D`](https://github.com/schwehr/Tracker-Component-Library/blob/master/Assignment%20Algorithms/2D%20Assignment/assign2D.m) function instead. It would be great to have it in Stone Soup, provided that `assign2D` has already been [implemented](https://stonesoup.readthedocs.io/en/latest/stonesoup.dataassociator.html#stonesoup.dataassociator.neighbour.GNNWith2DAssignment) to speed up the GNN algorithm.

**Comment by sdhiscocks** [comment]
I've opened #1033 which switches out the algorithm for the SciPy implementation (which is based off of linked MATLAB version).

Just as another suggestion, you could reduced/interpolated truth and tracks to reduce the number of timestamps to speed up metrics, if you don't really need metric at every timestep.
