### ISSUE TITLE
Value Error using a Parameterized Type as a Property (Python 3.12.4)

### ISSUE THREAD

**Issue by gawebb-dstl** [dstl/Stone-Soup#1094]
I get a Value Error using a Parameterized Type (e.g. `list[float]`) as a Property in Python 3.12.4. I don't get the error when using Python 3.9.4.

You can recreate this error with the following code snippet.
```
from stonesoup.base import Base, Property

class A(Base):
	numbers: set[int] = Property()
```
Output: `ValueError: Invalid type specification (set[int]) for property numbers of class A`

I've narrowed down the error to line 292 in base.py when `isinstance(property_type, type)` is used:
Python 3.9.4
```
print(isinstance(set[int], type))
>>> True 
```
Python 3.12.4
```
print(isinstance(set[int], type))
>>> False
```

**Comment by sdhiscocks** [comment]
I believe this will be fixed in c81dee27b787fcffe9261b3b2ba259655165efdb from #1092
