### ISSUE TITLE
Increase allowed line length

### ISSUE THREAD

**Issue by etfrogers-dstl** [dstl/Stone-Soup#161]
Is it time to change to a longer line-length standard in Stone Soup?

The current 80 character lines seem to me (and a couple of others I have spoken) to negatively affect code readability. Many lines of code have to be wrapped several times and would be clearer on one or two lines. 

From PEP8: "Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the line length limit up to 99 characters, provided that comments and docstrings are still wrapped at 72 characters."

Bear in mind that was the position in 2001,and monitors have only got wider since then. 
Switching to 99 chars, or even pycharm's default of 120 seems like a good idea to me.

The switch is a few-line, single-file push (either `tox.ini`, `setup.cfg`, `.pep8` or `.flake8`) and is, of course, backward compatible. No old code needs to be changed, but new code would have more flexibility.

Do people have any comments?

**Comment by sdhiscocks** [comment]
So even with screen real estate being larger, very long lines can be unreadable and can get messy are allows people to nest in more _if_ block, _for_ loops, etc. It also can become more difficult for side by side comparison, especially for 3-way merges (but these are rare to be fair).

We have a lot of equations and long variables names (which makes code more readable) that could really do with some more room, as they are becoming less readable by the time your forced to break them up over multiple lines. We also typically have the bulk of code in class methods, so lose 8 characters before you even get started.

There's always a balance to be had, but I think increasing to 99 characters would improve readability.

If we did make a change, I'd suggest we don't make one massive code change but allow the project to transition naturally as we make code changes.

**Comment by jmbarr** [comment]
<meh>

**Comment by jmbarr** [comment]
¯\_(ツ)_/¯

**Comment by DaveKirkland** [comment]
I don't really have a problem with this. Can a local flake8 configuration file be distributed with the project, so that it passes the flake8 testing? Or include instructions for how to manually configure this ourselves,

**Comment by etfrogers-dstl** [comment]
@DaveKirkland Yes, the flake8 configuration can be committed, if that what is wanted. I assume CircleCI would honour it (otherwise, we might have to configure that separately).

**Comment by rjgreen-dstl** [comment]
closed as addressed in #166
