### ISSUE TITLE
Implement a square root version of the Kalman Filter

### ISSUE THREAD

**Issue by jmbarr** [dstl/Stone-Soup#171]
Minimally this would just to be to create a `SquareRootKalmanUpdater` which executes the `update` function on a square root parameterisation of the covariance matrix. Such a recursion is more numerically stable than the usual Kalman version.

There are several versions of the how exactly to do $P = WW^T$, and the version I currently favour is from Andrews 1968. Which seems a touch outdated. If you have a preference, please detail below.

Would suggest that the class checks the format of the incoming covariance matrix and adjusts it if needed but returns the square root format. Or perhaps both? 

Also, no plans to do 'SquareRootKalmanPredictor`, because that wouldn't be worthwhile as it doesn't solve a problem related to numerical instabilities.

**Comment by jmbarr** [comment]
Created branch SqrtKalmanFilter. Intent is to build around a `SqrtGaussianState` type which stores the the covariance matrix in lower-triangular form ($L$) where the 'full' covariance matrix, $P = LL^T$.

It's then not clear whether it's then better to create a separate updater (`SqrtKalmanUpdater`) derived from `KalmanUpdater`, or add a new method to `KalmanUpdater`. Suggestions?

`KalmanPredictor` can probably be modified fairly straightforwardly.

**Comment by DaveKirkland** [comment]
> 
> It's then not clear whether it's then better to create a separate updater (`SqrtKalmanUpdater`) derived from `KalmanUpdater`, or add a new method to `KalmanUpdater`. Suggestions?
> 
> `KalmanPredictor` can probably be modified fairly straightforwardly.

After listening to your discussion with Simon this morning, that we it may prove useful to have so slightly different versions of the square root algorithm. In this case, I think it would be better to go via the subclass route rather than add additional methods to Updater class.

**Comment by jmbarr** [comment]
Thanks @paulhorridge. 

A couple of things if I may:

1. I'd originally imagined that the recursion would proceed by passing a mean and square-root matrix through the predict and update steps. Hence the need for a `sqrtGaussianState` class. If you're calculating the square root, updating and reconstituting the full covariance within the updater, then it won't be required. In fact we don't need a `sqrtKalmanUpdater`. We can just add code to the `KalmanUpdater` together with a flag that tells the object to use that method.
2. Do you have an test case where the square root form shows demonstrates its worth? I was going to spend a little time looking for ill-conditioned covariances, but if you already have examples please feel free to drop them in.

Cheers

**Comment by paulhorridge** [comment]
Hi Jordi,


  1.  I didn't think there was a SqrtGaussianState class (or it wasn't there yet) at the time I coded up the filter. I expect the filter would perform better if the full covariance was not calculated but I haven't integrated it in yet.
  2.  I don't, sorry. If you are happy to find some great, otherwise I could try?

Cheers,
Paul.

________________________________

**Comment by jmbarr** [comment]
See #213 for an idea. The logic for implementing the square root version of the update is now in the `KalmanUpdater.update()` function (and so is available to the EKF and UKF). 

There's a new test case which demonstrates a situation where the square root formulation succeeds as the vanilla version fails.

**Comment by jmbarr** [comment]
Ref #223. Happy weekend.

**Comment by sdhiscocks** [comment]
Closed with #223
