### ISSUE TITLE
Target simulator question/request/enhancement.

### ISSUE THREAD

**Issue by apiszcz** [dstl/Stone-Soup#196]
Is it possible to obtain a track identifier from the detection simulators?
In other cases where I generate the detection I use the metadata parameter / dictionary to specify the track identifier.

**Comment by sdhiscocks** [comment]
So there is a [TrueDetection](https://github.com/dstl/Stone-Soup/blob/ff666d6da7965a35ea241afca88ac46aeb1c4cf1/stonesoup/types/detection.py#L35) type that links a ground truth path to a detection. Is that what you require?

One issue is I don't think any of our sensors use this, which they really should.

**Comment by apiszcz** [comment]
It seems like we would want this for the simulated data.

I need to learn more about the groundtruth data structures.

Tx
