### ISSUE TITLE
SPIE notebook update, AttributeError: 'MultiTargetGroundTruthSimulator' object has no attribute '_groundtruth_paths'

### ISSUE THREAD

**Issue by apiszcz** [dstl/Stone-Soup#197]
Located this change, 

AttributeError: 'MultiTargetGroundTruthSimulator' object has no attribute '_groundtruth_paths'

kalman_tracker.detector._groundtruth

resolved with
kalman_tracker.detector.groundtruth

**Comment by sdhiscocks** [comment]
Resolved with newer tutorials.
