### ISSUE TITLE
Incorporating target feature into tracking

### ISSUE THREAD

**Issue by Huang-Chuan** [dstl/Stone-Soup#237]
Dear experts,
  Is there a way to incorporating target feature in tracking? My thoughts was to utilize target feature in gating and track scoring and update feature in each scan. But I am not sure how to do this. Is it the right way to put extracted target feature into detection metadata field and then modify associate and update method accordingly? Or there is another shortcut?

Many thanks.

**Comment by sdhiscocks** [comment]
Is this a feature you could add to the state vector, i.e. numerical value? Then you could add a random walk transition model for prediction.

**Comment by Huang-Chuan** [comment]
@sdhiscocks Yes, it is numerical value. However, I want to some fancy regression model to fit feature vector over scans.

**Comment by sdhiscocks** [comment]
So you could instead have it on your meta data for detections, which tracks will then also have that same meta data field (taking the value from most recent detection that was used to update it). You could then create a custom gater (like the FilteredDetectionsGater), which gates out those which value is outside of a tolerance.

**Comment by DaveKirkland** [comment]
@sdhiscocks What happens to the metadata when multiple measurements are blended together to form the update e.g. PDA or JPDA? Are there hooks available for the user to control what happens to the metadata in these cases?

**Comment by sdhiscocks** [comment]
@DaveKirkland the meta data is applied from all detections in reverse sorted order, such that "best" hypothesis takes preference.

You could customise the behavior by subclassing Track, and have initiator yield your subclass.
