### ISSUE TITLE
Files stay open after iterating CSVGroundTruthReader

### ISSUE THREAD

**Issue by DaveKirkland** [dstl/Stone-Soup#254]
After running over the generator for a CSVGroundTruthReader the file remains open. This caused a problem in git when switching development branches - the file couldn't be released because it was still in use.  See for example:
```
from stonesoup.reader.generic import CSVGroundTruthReader

ground_truth_reader = CSVGroundTruthReader(
    path='UAV_Rot.csv',
    state_vector_fields=['longitude', 'Vx m/s', 'latitude', 'Vy m/s', 'altitude (m)'],
    time_field='time',
    path_id_field='groupNb',
)

for cnt, item in enumerate(ground_truth_reader):
    print("Count is " + str(cnt))

ground_truth_reader._file.closed
```

The  last line returns False. To close the file you need to either restart the kernel or do *ground_truth_reader._file.close()*. This works in this case - not sure if it works when we chain multiple readers/feeders together.

We may need to add and explicit close() to the interface and/or rethink some of the design.

**Comment by DaveKirkland** [comment]
After playing around with this some more - If I manually close the file and then iterate over the file again and check the file - it is still closed. So I'm not sure if there's still an open file somewhere or we've lost the variable point to it. Here's the example:
```
for cnt, item in enumerate(ground_truth_reader):
    pass

print(ground_truth_reader._file.closed)
ground_truth_reader._file.close()

for cnt, item in enumerate(ground_truth_reader):
    pass
    
print(ground_truth_reader._file.closed)
```
The output is False and then True.

**Comment by DaveKirkland** [comment]
@sdhiscocks Looking at the way we iterate over the readers:
If I have the following code:
```
det_reader = CSVDetectionReader(...)
tmp = iter(det_reader)
next(tmp)
```
When det_reader is created it opens the file and the file handle is stored under det_reader._file.
When we iterate over the det_reader we execute the CSVDetectionReader.detections_gen() which  has it's own context manager i.e. it executes:
```
with self.path.open(encoding=self.encoding, newline='') as csv_file:
```
which also creates an open file handle.

When the loop finishes the context manager and it closes the file.
However we still have the open file handle when we created det_reader. The only time det_reader.__exit__() is called is if we del(det_reader) or restart the python kernel.
 
I can't see any code that actually reads from the file handle stored in det_reader._file. It is the file handle stored in det_reader._file that remains open and causes the problem.

**Comment by sdhiscocks** [comment]
Yeah, that's not good. Probably shouldn't be opening the file on initialisation either. Suggest we just simplify the _FileReader_ classes by removing the `self._file` stuff.
