### ISSUE TITLE
Is Folium a new requirement?

### ISSUE THREAD

**Issue by etfrogers-dstl** [dstl/Stone-Soup#259]
One of the merged demos, `AIS_Solent_Tracker`, fails to build in Sphinxwithout the `folium` package installed. Should this be added to the dependencies list?

**Comment by apiszcz** [comment]
I had the same dependency on my recent sphix_build.

**Comment by DaveKirkland** [comment]
I think the list of dependencies probably needs to be updated. To generate the documentation I had to add sphinx-gallery and sphinx-rtd-theme.

We may want to separate the actually Stone Soup dependencies from the one that examples or demos use.

**Comment by etfrogers-dstl** [comment]
Actually, I had noted both those @DaveKirkland mentions as well.

**Comment by sdhiscocks** [comment]
_Folium_ is needed to build documentation. It was added to _dev_ dependencies in d3bfa55794f850acc94d7523fd7c1f71adce7f7c

Do you think it would be better to have separate _dev_ and _doc_ dependencies?

**Comment by etfrogers-dstl** [comment]
I was looking at the list in the [Readme](https://github.com/dstl/Stone-Soup/blob/master/README.md)

This still says:

> For development the following libraries are also recommended:
> 
> | Name | License |
> | ---- | ------- |
> | [Sphinx](https://www.sphinx-doc.org/) | BSD |
> | [pytest](https://docs.pytest.org/) | MIT |
> | [Flake8](https://flake8.pycqa.org/) | MIT |
> | [Coverage.py](https://coverage.readthedocs.io/) | Apache 2.0 |

Perhaps it should be updated?

**Comment by sdhiscocks** [comment]
> I was looking at the list in the [Readme](https://github.com/dstl/Stone-Soup/blob/master/README.md)
> 
> This still says:
> 
> > For development the following libraries are also recommended:
> > 
> > 
> > 
> > Name
> > License
> > 
> > 
> > 
> > 
> > [Sphinx](https://www.sphinx-doc.org/)
> > BSD
> > 
> > 
> > [pytest](https://docs.pytest.org/)
> > MIT
> > 
> > 
> > [Flake8](https://flake8.pycqa.org/)
> > MIT
> > 
> > 
> > [Coverage.py](https://coverage.readthedocs.io/)
> > Apache 2.0
> 
> Perhaps it should be updated?

Yes. That's very out of date.
