### ISSUE TITLE
MatLab code for Joint Probability Data Association Filter

### ISSUE THREAD

**Issue by tsameema** [dstl/Stone-Soup#265]
Can anyone provide MatLab code for Joint Probability Data Association Filter. I have searched, but only C+ or python codes are available. And I get only one link of MatLab. That is https://se.mathworks.com/help/fusion/ref/trackerjpda-system-object.html

Please suggest other links for code. It will be a great favor.

**Comment by sdhiscocks** [comment]
Hi @tsameema. I can't point you to something directly, but you may find what your after in the [Tracker Component Library](https://github.com/USNavalResearchLaboratory/TrackerComponentLibrary).

You can interface Matlab with Python (we have draft interface into Stone Soup in #105), so may be able to use implementation in Stone Soup if that's suitable.
