### ISSUE TITLE
ModuleNotFoundError: No module named 'stonesoup.detector.tensorflow'

### ISSUE THREAD

**Issue by sakalu** [dstl/Stone-Soup#276]
Hi,

When I execute the Video_Processing.py I downloaded from Stone Soup Demonstration, I got an error message as below,

  File "Video_Processing.py", line 261, in <module>
    from stonesoup.detector.tensorflow import TensorFlowBoxObjectDetector
ModuleNotFoundError: No module named 'stonesoup.detector.tensorflow'

I checked and does found no module named 'stonesoup.detector.tensorflow'. Does anyone know how to solve this problem? Thanks!!

**Comment by DaveKirkland** [comment]
Check that you have the latest version of the master branch. There should be a tensorflow.py file in the stonesoup\detector\ directory. See here [detector directory](https://github.com/dstl/Stone-Soup/tree/master/stonesoup/detector).

**Comment by sakalu** [comment]
> Check that you have the latest version of the master branch. There should be a tensorflow.py file in the stonesoup\detector\ directory. See here detector directory.

Thanks. this problem has been solved
