### ISSUE TITLE
Issue with gauss2sigma() and int type StateVectors

### ISSUE THREAD

**Issue by sglvladi** [dstl/Stone-Soup#277]
An issue has been observed which causes the sigma points generated by ``gauss2sigma()`` to be cast to ``ints`` when a state is provided with a state vector whose elements are all ``ints``. 

A notebook that reproduces and explains the issue can be found [here](https://gist.github.com/sglvladi/8d1ff25944876bdbb6caf4058ca7cfe5)

**Comment by sdhiscocks** [comment]
So `gauss2sigma` originally didn't work with ints, and #198 was implemented to fix and also maintain ints. Guess this isn't desired behavior?

**Comment by sglvladi** [comment]
Unless the models and UKF parameters are specifically chosen such that the sigma points end up being ints (which is highly unlikely), the use of ints results in skewed sigma points which cause issues when running UKF as pointed out by @jmbarr in #255. I think that most users will expect things to work fine even if they use ints to define their state vectors.

**Comment by sdhiscocks** [comment]
> I think that most users will expect things to work fine even if they use ints to define their state vectors. 

Yeah, that makes sense. Should be easy to fix to change dtype of sigma points after `np.tile`. Should only change int to float however, to still allow object dtype, or only change if not object.

**Comment by sglvladi** [comment]
Great! You are right. When dtype is object then the method works just fine. 

Does the code below look ok? It seems to do the job in my tests. 

``` python
if np.issubdtype(sigma_points.dtype, np.integer):
    sigma_points = sigma_points.astype(float)
```
