### ISSUE TITLE
Any ideas on TO-MHT implementation?

### ISSUE THREAD

**Issue by Huang-Chuan** [dstl/Stone-Soup#280]
Dear experts, 

I am currently working on TO-MHT algorithms. I was wondering is it possible(convenient) to implement TO-MHT using current available modules? 

I appreciate your valuable advice!

Sincerely,
Chuan

**Comment by sdhiscocks** [comment]
We've got a lot of building blocks. I think we'd need to create a `Tracker` class, which doesn't have a `DataAssociator` but instead an `Hypothesiser` (which would include `Gater` classes), and then handles creation/pruning of track tree structure. We could then create different tracker classes, or maybe pass in different pruning classes, to create different variants.

It may make sense to have this track tree structure have a `set` like interface which is yielded from the tracker, which then yields the current time "best" tracks when iterating over. This way you could create a copy of the structure at each timestep if you wanted to understand how MHT evolved over time, as well as providing familiar interface to other components.

**Comment by Huang-Chuan** [comment]
Thank you! I'll work on it after I discuss with my colleagues. Hope there will be a meaningful conversation going on.

**Comment by sdhiscocks** [comment]
We are currently commissioning development of MHT into Stone Soup, so hopefully see something in coming months. I've reopened this issue so we can track it here.

@Bebert98 Maybe you could open a [discussion](https://github.com/dstl/Stone-Soup/discussions) with the issues you're having and we can try and help.

You may also be interested in #568. I've just been updating this to latest version and adding an example, which I'll push in draft form soon.
