### ISSUE TITLE
Unexpected Behavior with default values for properties

### ISSUE THREAD

**Issue by gawebb-dstl** [dstl/Stone-Soup#293]
I ran into a bug yesterday, which really confused me for a long time. It due to default value of a Property is linked. So all objects with a default value point to the same value. The code snippet below highlights this example. 

```
from stonesoup.base import Base, Property

class ExampleClass(Base):
    a_list = Property(list, default=list(), doc='Todo')

    '''  This fixes the problem
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.a_list = []'''

eg_class_1 = ExampleClass()
eg_class_2 = ExampleClass()

print(eg_class_1.a_list is eg_class_2.a_list) # Prints True
eg_class_1.a_list.append(1)
print(eg_class_2.a_list) # Prints [1]
```

For me the above behavior is unexpected. I'm not sure if this something that could be changed. Looking at the code in base.py it looks like it's outside of stonesoup. However would it be possible to add a warning within the code. If default is mutable, raise a warning. 

This is a suggestion. I'd like to hear your thoughts?

**Comment by sdhiscocks** [comment]
This is just a feature of Python, rather than a Stone Soup issue. Default arguments shouldn't be mutable. Better to use `None` and create an empty list on initialisation. Not sure we should do something special in Stone Soup for this, as is a common Python gotcha.
