### ISSUE TITLE
How to use Particle Filtering for multi-target Tracking in Stone Soup

### ISSUE THREAD

**Issue by sakalu** [dstl/Stone-Soup#297]
Hi,

First of all, I would like to thank you for providing us this this excellent software framework.

I have got a question of multi-target Tracking using Particle Filtering in Stone Soup, the provided demonstration "Tracking AIS Reports Using Stone Soup" for example. The Particle Filtering tracker I try to build include with the following parts, however, I have no idea how to deal with the "PRIOR ESTIMATE" and fit it onto this tracker (or let's say MultiTargetTracker()). I would appreciate it if you could advise me of this. Thanks!!!

predictor = ParticlePredictor(transition_model)
resampler = SystematicResampler()
updater = ParticleUpdater(measurement_model, resampler)

tracker = MultiTargetTracker(
    initiator=initiator,
    deleter=deleter,
    detector=detector,
    data_associator=data_associator,
    updater=updater,
)

**Comment by oharrald-Dstl** [comment]
Hello, what initiator are you using?

**Comment by sakalu** [comment]
Thank you for your reply. I am just coming into this area of tracking and aiming to accelerated learning using the tutorials/examples/demonstrations. As all the examples are either Kalman/Particle Filter single-target Tracker or Kalman Filter multi-target Tracker (Tracking AIS Reports Using Stone Soup for example), I try to implement "Particle Filter multi-target Tracker" by modifying the example "Tracking AIS Reports Using Stone Soup" provided DSTL GitHub.

So the initiator and deleter (as below) I am using are just the same as the example. Thanks!!

initiator = SimpleMeasurementInitiator(
    GaussianState([[0], [0], [0], [0]], np.diag([0, 10, 0, 10])),
    measurement_model)

deleter = UpdateTimeDeleter(datetime.timedelta(minutes=10))

**Comment by sakalu** [comment]
Thank you for your reply. I am just coming into this area of tracking and aiming to accelerated learning using the tutorials/examples/demonstrations. As all the examples are either Kalman/Particle Filter single-target Tracker or Kalman Filter multi-target Tracker (Tracking AIS Reports Using Stone Soup for example), I try to implement "Particle Filter multi-target Tracker" by modifying the example "Tracking AIS Reports Using Stone Soup" provided DSTL GitHub.

So the initiator and deleter (as below) I am using are just the same as the example. Thanks!!

initiator = SimpleMeasurementInitiator(
    GaussianState([[0], [0], [0], [0]], np.diag([0, 10, 0, 10])),
    measurement_model)

deleter = UpdateTimeDeleter(datetime.timedelta(minutes=10))

**Comment by sakalu** [comment]
Thank you for your reply. I am just coming into this area of tracking and aiming to accelerated learning using the tutorials/examples/demonstrations. As all the examples are either Kalman/Particle Filter single-target Tracker or Kalman Filter multi-target Tracker (Tracking AIS Reports Using Stone Soup for example), I try to implement "Particle Filter multi-target Tracker" by modifying the example "Tracking AIS Reports Using Stone Soup" provided DSTL GitHub.

So the initiator and deleter (as below) I am using are just the same as the example. Thanks!!

initiator = SimpleMeasurementInitiator(
    GaussianState([[0], [0], [0], [0]], np.diag([0, 10, 0, 10])),
    measurement_model)

deleter = UpdateTimeDeleter(datetime.timedelta(minutes=10))

**Comment by sakalu** [comment]
Thank you for your reply. I am just coming into this area of tracking and aiming to accelerated learning using the tutorials/examples/demonstrations. As all the examples are either Kalman/Particle Filter single-target Tracker or Kalman Filter multi-target Tracker (Tracking AIS Reports Using Stone Soup for example), I try to implement "Particle Filter multi-target Tracker" by modifying the example "Tracking AIS Reports Using Stone Soup" provided DSTL GitHub.

So the initiator and deleter (as below) I am using are just the same as the example. Thanks!!

initiator = SimpleMeasurementInitiator(
    GaussianState([[0], [0], [0], [0]], np.diag([0, 10, 0, 10])),
    measurement_model)

deleter = UpdateTimeDeleter(datetime.timedelta(minutes=10))

**Comment by sakalu** [comment]
Thank you for your reply. I am just coming into this area of tracking and aiming to accelerated learning using the tutorials/examples/demonstrations. As all the examples are either Kalman/Particle Filter single-target Tracker or Kalman Filter multi-target Tracker (Tracking AIS Reports Using Stone Soup for example), I try to implement "Particle Filter multi-target Tracker" by modifying the example "Tracking AIS Reports Using Stone Soup" provided DSTL GitHub.

So the initiator and deleter (as below) I am using are just the same as the example. Thanks!!

initiator = SimpleMeasurementInitiator(
    GaussianState([[0], [0], [0], [0]], np.diag([0, 10, 0, 10])),
    measurement_model)

deleter = UpdateTimeDeleter(datetime.timedelta(minutes=10))

**Comment by oharrald-Dstl** [comment]
Utilise the 'GaussianParticleInitiator'.
eg. initiator = GaussianParticleInitiator(initiator=initiator, number_particles=200)

This will initiate tracks as before, but remake tracks' initial states to be particle states instead by distributing particles according to the prior state you have already defined.

**Comment by oharrald-Dstl** [comment]
The 'Multi-Sensor Moving Platform Simulation' example uses the 'GaussianParticleInitiator', in-case you would like an example.
https://stonesoup.readthedocs.io/en/latest/auto_examples/Moving_Platform_Simulation.html#sphx-glr-auto-examples-moving-platform-simulation-py

**Comment by sakalu** [comment]
> Utilise the 'GaussianParticleInitiator'.
> eg. initiator = GaussianParticleInitiator(initiator=initiator, number_particles=200)
> 
> This will initiate tracks as before, but remake tracks' initial states to be particle states instead by distributing particles according to the prior state you have already defined.

Thank you so much for the information. Yes, I have modified the example "Tracking AIS Reports Using Stone Soup (Kalman filtering case)" by Utilising the 'GaussianParticleInitiator' and no error was produced. However, I found the results interesting that the generated number of tracks (200) which is different from and more than the number of tracks (121) generated in Kalman filtering case. Take the vessel (MMSI= 235072757) for example, one track generated in Kalman filtering case but five tracks generated in Particle filtering case. I am not sure if it is normal or something wrong with my modification. Thanks!!

Below is the parts I modified from the example,

from stonesoup.predictor.particle import ParticlePredictor
predictor = ParticlePredictor(transition_model)

from stonesoup.resampler.particle import SystematicResampler
resampler = SystematicResampler()

from stonesoup.updater.particle import ParticleUpdater
updater = ParticleUpdater(measurement_model, resampler)

initiator = SimpleMeasurementInitiator(GaussianState([[0], [0], [0], [0]], np.diag([0, 10, 0, 10])), measurement_model)

from stonesoup.initiator.simple import GaussianParticleInitiator
initiator = GaussianParticleInitiator(initiator=initiator, number_particles=200)

from stonesoup.tracker.simple import MultiTargetTracker
tracker = MultiTargetTracker(
    initiator=initiator,
    deleter=deleter,
    detector=detector,
    data_associator=data_associator,
    updater=updater,
)

**Comment by sakalu** [comment]
> The 'Multi-Sensor Moving Platform Simulation' example uses the 'GaussianParticleInitiator', in-case you would like an example.
> https://stonesoup.readthedocs.io/en/latest/auto_examples/Moving_Platform_Simulation.html#sphx-glr-auto-examples-moving-platform-simulation-py

Thank you for the information. I will look at this example to get me familiar with Particle filtering.

**Comment by oharrald-Dstl** [comment]
Adding more particles in the initiator should help, though it will slow down tracker.

**Comment by sakalu** [comment]
> Adding more particles in the initiator should help as having a better representation of the underlying distributions may lead to less tracks being generated.

Yes, it works. Thanks!!!

**Comment by oharrald-Dstl** [comment]
No problem.
