### ISSUE TITLE
The "edit on Github" for a tutorial goes to a 404 page

### ISSUE THREAD

**Issue by PhilipOakley** [dstl/Stone-Soup#300]
I navigated to https://stonesoup.readthedocs.io/en/latest/auto_tutorials/01_KalmanFilterTutorial.html#sphx-glr-auto-tutorials-01-kalmanfiltertutorial-py from the introduction page by clinking the link there.

I was wanting to look at the math formatting so clicked the (top right) "Edit on GitHub" icon link (adjacent the title line).

It looks like the link presented there is called https://github.com/dstl/Stone-Soup/blob/master/docs/source/auto_tutorials/01_KalmanFilterTutorial.rst and it should not have the "auto_" within the path. 

I haven't followed around the loop to discover where the issue starts, though I guess it's implicitly programmatic.

**Comment by sdhiscocks** [comment]
The tutorials/examples/demos are generated dynamically from code, so the actual RST files are generated on build, so can't be found in the repository.

You'll find the Python code that they are generated from here:
 - Tutorials: https://github.com/dstl/Stone-Soup/tree/master/docs/tutorials
 - Examples: https://github.com/dstl/Stone-Soup/tree/master/docs/examples
 - Demos: https://github.com/dstl/Stone-Soup/tree/master/docs/demos

I'll have to see if we can fix those links. They are generated by the read the docs, so not 100% sure if/how we can fix them at the moment.

**Comment by PhilipOakley** [comment]
> They are generated by the read the docs

Are you meaning this: https://github.com/dstl/Stone-Soup/blob/master/.readthedocs.yml ?

**Comment by sdhiscocks** [comment]
So looks like issue is related to how the template for the documentation works, which reasonably isn't aware that some of our documentation is auto generated. I've overridden the template in commit c29fa95 to point to correct file for auto generated content. Once #302 is merged, you should see this fixed on documentation pages.

**Comment by PhilipOakley** [comment]
Yes, that fix looks to be suitable far away from the discovered problem to make it hard to find (I couldn't find it even with browsing and linking through the code and looking at/up Sphinx).

**Comment by sdhiscocks** [comment]
Thanks for raising this issue @PhilipOakley. Should be fixed now.

**Comment by PhilipOakley** [comment]
> Should be fixed now.

Success! (I needed to reload the page locally as it had been cached by my browser)

Aside: It might be worth a short `README` doc in https://github.com/dstl/Stone-Soup/tree/master/docs that described the tortuous route around the doc build scheme (or at least a bread crumbs trail to include the implicit steps) to help others dive in if they have any problems.
