### ISSUE TITLE
Read AIS from AIS streams in real-time.

### ISSUE THREAD

**Issue by sakalu** [dstl/Stone-Soup#313]
Hi,

In the example of Tracking AIS Reports Using Stone Soup, the detector was prepared for the AIS data, which is in a CSV file, using the Stone Soup generic CSV reader (CSVDetectionReader). So I am wondering if there is the reader built and provided in Stone Soup for reading the AIS real-time streams.  Thanks!!

Saka

**Comment by apiszcz** [comment]
Saka: They are named feeders, https://stonesoup.readthedocs.io/en/latest/stonesoup.feeder.html

**Comment by sdhiscocks** [comment]
@sakalu So the trackers are designed to work with streaming data, but we don't have anything that reads a streams of AIS. You'll need to create a custom reader which generates timestamps and sets of  `Detection` objects.

What is your source of streaming data? Over TCP/IP or USB Serial?

**Comment by sakalu** [comment]
> @sakalu So the trackers are designed to work with streaming data, but we don't have anything that reads a streams of AIS. You'll need to create a custom reader which generates timestamps and sets of `Detection` objects.
> 
> What is your source of streaming data? Over TCP/IP or USB Serial?

Thanks. Steven.

> Saka: They are named feeders, https://stonesoup.readthedocs.io/en/latest/stonesoup.feeder.html

Thanks. Ap.

**Comment by sakalu** [comment]
> Saka: They are named feeders, https://stonesoup.readthedocs.io/en/latest/stonesoup.feeder.html

**Comment by sakalu** [comment]
> @sakalu So the trackers are designed to work with streaming data, but we don't have anything that reads a streams of AIS. You'll need to create a custom reader which generates timestamps and sets of `Detection` objects.
> 
> What is your source of streaming data? Over TCP/IP or USB Serial?

Thanks. Steven.

As Ap's reply above that the one taking the AIS real-time streams is named "feeder" (Is it corrected?), and the feeder’s primary role in Stone soup is to take detection data from inputs into the framework, and feed them into the tracking algorithms. Or feeder classes are for manipulating data going into the tracker. 
So can I say that there is no feeder built in Stone Soup for taking the AIS real-time streams and therefore we need to create a custom one (reader or feeder?). I will appreciate it if you can clarify this.

I am a beginner to use the tracker taking the AIS real-time streams and I am wondering what I need to consider in term of TCP/IP or USB Serial. Thank you so much.

**Comment by sdhiscocks** [comment]
So data gets into Stone Soup via Readers (e.g. from a CSV file, from a database, IP socket), and Feeders' role is manipulating data before they go into the tracker (e.g. coordinate conversion, de-duplication,  filtering by metadata).

So all you should need to create is a `DetectionReader` (by inheriting from that class) and implement the `detections_gen` method. This method should loop doing the following:
- read some data from your source;
- create `Detection` objects;
- possibly group multiple by time;
- and yield a timestamp and set of these `Detection` objects.

**Comment by sakalu** [comment]
> So data gets into Stone Soup via Readers (e.g. from a CSV file, from a database, IP socket), and Feeders' role is manipulating data before they go into the tracker (e.g. coordinate conversion, de-duplication, filtering by metadata).
> 
> So all you should need to create is a `DetectionReader` (by inheriting from that class) and implement the `detections_gen` method. This method should loop doing the following:
> 
> * read some data from your source;
> * create `Detection` objects;
> * possibly group multiple by time;
> * and yield a timestamp and set of these `Detection` objects.

Hi Steven,

I really appreciate your taking the time to make it clear to me.
