### ISSUE TITLE
Read frames from real-time video streams from USB camera

### ISSUE THREAD

**Issue by sakalu** [dstl/Stone-Soup#325]
Hi experts,

Thank you for providing an example of how to build a FFmpegVideoStreamReader for a camera which broadcasts its feed through a public RTSP stream. I were wondering whether I could use the component of FFmpegVideoStreamReader for reading real-time video streams from USB camera. Thank you!!

Kind regards,

**Comment by sdhiscocks** [comment]
@sakalu It is possible, but requires a slight modification, which I have done, but hadn't got around to opening a PR, as it was a bit of a side project. The change is in commit 97a00e37b72c9fa400ae081d477a3cb284f0f01a, which you can use for example:
```python
from stonesoup.reader.video import FFmpegVideoStreamReader
frame_size = (640, 360)
in_opts = {'f': 'dshow', 'threads': 1, 'fflags': 'nobuffer'}
out_opts = {'f': 'rawvideo', 'pix_fmt': 'rgb24'}
input_= 'video=Integrated Webcam'
filter_ = ('scale', frame_size, {})
video_reader = FFmpegVideoStreamReader(
    input_, input_opts=in_opts, output_opts=out_opts, filter=filter_, frame_size=frame_size)
```
This also uses another added feature of letting you use filters, in this case scaling the video input.

This is using _dshow_ ffmpeg plugin on Windows. You can get a list of your devices with:
```sh
ffmpeg -list_devices true -f dshow -i dummy
```

**Comment by sakalu** [comment]
> @sakalu It is possible, but requires a slight modification, which I have done, but hadn't got around to opening a PR, as it was a bit of a side project. The change is in commit [97a00e3](https://github.com/dstl/Stone-Soup/commit/97a00e37b72c9fa400ae081d477a3cb284f0f01a), which you can use for example:
> 
> ```python
> from stonesoup.reader.video import FFmpegVideoStreamReader
> frame_size = (640, 360)
> in_opts = {'f': 'dshow', 'threads': 1, 'fflags': 'nobuffer'}
> out_opts = {'f': 'rawvideo', 'pix_fmt': 'rgb24'}
> input_= 'video=Integrated Webcam'
> filter_ = ('scale', frame_size, {})
> video_reader = FFmpegVideoStreamReader(
>     input_, input_opts=in_opts, output_opts=out_opts, filter=filter_, frame_size=frame_size)
> ```
> 
> This also uses another added feature of letting you use filters, in this case scaling the video input.
> 
> This is using _dshow_ ffmpeg plugin on Windows. You can get a list of your devices with:
> 
> ```shell
> ffmpeg -list_devices true -f dshow -i dummy
> ```

Hi Steven,

Thank you so much for providing me with this useful information.

**Comment by sakalu** [comment]
Hi Steven,

I have modified the reader/video.py based on the change in commit 97a00e3, but got a error message below while I imported FFmpegVideoStreamReader (from stonesoup.reader.video import FFmpegVideoStreamReader). I was wondering if you knew what cause this error. Thanks!


 File "C:\Users\sakal\Stone-Soup\stonesoup\reader\video.py", line 130, in FFmpegVideoStreamReader
    doc="Input source to read video stream from, passed as input file argument. This can "
TypeError: __init__() missing 1 required positional argument: 'cls'

**Comment by sdhiscocks** [comment]
@sakalu You won't be able to simply copy the one file, as there are other changes in Stone Soup. Hopefully #331 will be merged soon, but in the meantime you can install via: `pip install git+https://github.com/dstl/Stone-Soup.git@97a00e37b72c9fa400ae081d477a3cb284f0f01a#egg=stonesoup`

**Comment by sakalu** [comment]
> @sakalu You won't be able to simply copy the one file, as there are other changes in Stone Soup. Hopefully #331 will be merged soon, but in the meantime you can install via: `pip install git+https://github.com/dstl/Stone-Soup.git@97a00e37b72c9fa400ae081d477a3cb284f0f01a#egg=stonesoup`

Hi Steven. Thanks for the useful information. 

In the example of using VideoClipReader to read video frames, it returns a "generator" of frames (60 frames in this example) for each time step that we can visualize these frames as the example code (for timestamp, frame in frame_reader: .......). 
 
FFmpegVideoStreamReader also returns a generator of frames for each time step and I was wonder if it return "single frame" for each time step as it is for "real-time". If so, how do I visualize these frames. Thank you.

**Comment by sdhiscocks** [comment]
[Here's an example Notebook which I've used for testing](https://gist.github.com/sdhiscocks/5ebef040670ef1eebaea652405c93a93). This uses the `async` flag which TensorFlow/TensorNets detector uses, so it only takes the latest frame. The tracking part updates the output every loop, so you get live(-ish depending on GPU) image.

I'm wondering now if we should move the `async` logic to the FFmpegVideoStreamReader now that I think about it?

**Comment by sakalu** [comment]
Hi Steven. Thanks again for your time and help. 
I have Installed via: pip install git+https://github.com/dstl/Stone Soup.git@97a00e37b72c9fa400ae081d477a3cb284f0f01a#egg=stonesoup 

I have tried to execute the example Notebook, but got errors for the following, and were wondering if there are some things I missed. Thanks!!

1) video_reader = FFmpegVideoStreamReader(
    input_, input_opts=in_opts, output_opts=out_opts, filters=filters, frame_size=frame_size)

    TypeError: got an unexpected keyword argument 'filters'

2)from stonesoup.detector.tensornets import TensorNetsBoxObjectDetector, Networks

  ImportError: cannot import name 'TensorNetsBoxObjectDetector' from 'stonesoup.detector.tensornets' (C:\Users\sakal\Anaconda3\envs\tensorflow_gpu\lib\site-packages\stonesoup\detector\tensornets.py)

**Comment by sdhiscocks** [comment]
Ah, sorry that notebook was using latest on that branch, so commit hash in the install was incorrect.

This should work, using the latest on that branch: `pip install git+https://github.com/dstl/Stone-Soup.git@tensornets#egg=stonesoup`

**Comment by sakalu** [comment]
> Ah, sorry that notebook was using latest on that branch, so commit hash in the install was incorrect.
> 
> This should work, using the latest on that branch: `pip install git+https://github.com/dstl/Stone-Soup.git@tensornets#egg=stonesoup`

Hi Steven. Thanks again for your help.  I hope you have had a great holiday.
There is no error message but just nothing (video expected?) coming out. Is there anything I need to do regarding connecting the webcam to the PC?  Thanks !!

**Comment by sdhiscocks** [comment]
@sakalu So as this uses _ffmpeg_, it's probably worth checking that running it on the command line works okay with your camera to get your settings right. You should hopefully be able to just use those settings into `FFmpegVideoStreamReader`.
