### ISSUE TITLE
Curious Angle error

### ISSUE THREAD

**Issue by jmbarr** [dstl/Stone-Soup#341]
`from stonesoup.types.angle import Angle`

In[---]: a = Angle(PI)
In[---]: a
Out[---]: Angle(3.141592653589793)
In[---]: np.isfinite(a)
Traceback (most recent call last):
  <blah blah>
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

So even though Angle a is recognisable as a number (PI), it isn't parsed as finite. (This also means you can't use np.isclose(), perhaps other functions, which are useful.)

Is this worth fixing?

**Comment by oharrald-Dstl** [comment]
Looks like it is due to the data type being a Python object, rather than a floating point type.
A way around that would be to check `np.array(a, dtype=float)` instead. Not sure that's what you'd be after though.

**Comment by jmbarr** [comment]
> Looks like it is due to the data type being a Python object, rather than a floating point type.
> 
Yes, but:

In[---]: b = a + 1
In[---]:  b > a
Out[---]: True
In[---]: b
Angle(4.141592653589793)

So Angle has some number-like behaviour, presumably because functions like __gt__() etc have been overwritten. Question is whether it's worth doing this for the function that tests for finiteness.

**Comment by jmbarr** [comment]
Given [this](https://github.com/numpy/numpy/issues/7431]) it looks like the proper solution requires modifying numpy (so that ufunc recognises Angle as like a float). I imagine it's not a high priority for them - for example datetime objects chuck the same error. 

I guess for now we just use the expedient method of comparing values rather than objects (e.g. `np.isclose(a._value, b._value)`). Or use @oharrald-Dstl's covert to floating point arrays, above.

I'll close the issue.
