### ISSUE TITLE
The _from_state() stuff broke astro code

### ISSUE THREAD

**Issue by jmbarr** [dstl/Stone-Soup#349]
It seems that #337 broke some code I had for doing EKF/UKF on orbits. I seem to be attaching the timestamp keyword twice but can't see where it's doing it. See (you need the Orbital branch): [this gist](https://gist.github.com/jmbarr/0a82def2b1ed287d7d020314638e4f33).

This used to work and I can't work out what's going on. Any ideas?

**Comment by sdhiscocks** [comment]
Looks like issue of argument order of the `OrbitalState` being different from `GaussianState`

Should `covar` be optional? If not, then simply moving this to top of list of properties should work, removing default. Otherwise you could inherit from `GaussianState`, which would make argument order the same. It may be best to inherit from `GaussianState` anyway?

**Comment by jmbarr** [comment]
No. Get the same error. Still trying to pass two timestamps. 

More generally `OrbitalState` shouldn't inherit from `GaussianState` because an orbital state doesn't have to be (indeed is often far from) Gauss-distributed. On the other hand the KF family require this parameterisation so strictly speaking I should probably be create `GaussianOrbitalState` for use with the EKF/UKF/xKF.

**Comment by jmbarr** [comment]
An `OrbitalState` which inherits from `GaussianState` works. Don't like that but making it difficult to use a `xKalmanPredictor` with non-Gaussian states might be a worthwhile thing. 

(Still can't work out why it doesn't work just inheriting from State.)

**Comment by jmbarr** [comment]
A very small amount of extra thought leads me to the conclusion that a `GaussianOrbitalState` is the way forward. This will inherit from `GaussianState` and `OrbitalState` and rather elegantly requires no new code while emphasising that you need a Gaussian parameterisation to use the Kalman predictors/updaters. I'll modify #278.

Later I'll try the same thing with the particle filter.

**Comment by jmbarr** [comment]
Fixed in #278 .
