### ISSUE TITLE
Codecov had a security breach that could steal credentials

### ISSUE THREAD

**Issue by PhilipOakley** [dstl/Stone-Soup#436]
It has been reported that Covecov had a security breach that could steal credential keys and passwords, detailed here https://arstechnica.com/gadgets/2021/04/backdoored-developer-tool-that-stole-credentials-escaped-notice-for-3-months/

Hopefully the project isn't affected.

**Comment by sdhiscocks** [comment]
Thanks for the heads up @PhilipOakley. We also got notification from CodeCov least week and have dealt with it.
