### ISSUE TITLE
Movable class has no statevector property but the function tries to edit the value of the property

### ISSUE THREAD

**Issue by gawebb-dstl** [dstl/Stone-Soup#454]
https://github.com/dstl/Stone-Soup/blob/1c23acf28cab48cc2f63a8dd5bff20c8be679efa/stonesoup/movable/movable.py#L209

**Comment by sdhiscocks** [comment]
This should be proxied to the underlying state. Are you getting an error?

**Comment by gawebb-dstl** [comment]
It was user error *facepalm*

I **was** getting an error `AttributeError: 'FixedMovable' object has no attribute 'state_vector'`. The issue was that I had initialised a `FixedPlatform` with `states=[[0,0,0]]`, I should have called it with `states=[State([0,0,0])]` It didn't lead to an error in the creation of the `FixedPlatform` object but lead to problems later down the line
