### ISSUE TITLE
SIAP Metrics Table

### ISSUE THREAD

**Issue by apiszcz** [dstl/Stone-Soup#457]
The SIAP metrics table works fine in the example Metrics python notebook. I am interested in saving the table to a png file. When I try this I am only seeing a part of a single row. An HTML output option might be useful in some cases.

![siap](https://user-images.githubusercontent.com/1430861/124289790-b3635500-db20-11eb-9ab7-18c32df9efac.png)

**Comment by sdhiscocks** [comment]
This is a common issue with _matplotlib_, often cutting off annotations and tables, etc. Addding `bbox_inches='tight'` to the `savefig` arguments should resolve it.

As this is image generated in _matplotlib_ currently, it wouldn't be possible to create HTML. You could do something like embed as data URI like suggested in [this answer on StackOverflow](https://stackoverflow.com/a/48717971).

**Comment by apiszcz** [comment]
Thank you for the response.

bbox_inches='tight'  produces the following output from plt.savefig('test3.png',bbox_inches='tight')
![test3](https://user-images.githubusercontent.com/1430861/124463614-20fdc400-dd61-11eb-9558-423764706509.png)

**Comment by sdhiscocks** [comment]
Interesting.

Does this work?
```python
table = SIAPTableGenerator(...).compute_metric()
table.figure.savefig('test.png',  bbox_inches='tight')
```

**Comment by apiszcz** [comment]
No. I tried this also
(Pdb) plt.tight_layout()
<stdin>:1: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all axes decorations.

**Comment by sdhiscocks** [comment]
I've just opened a PR that will hopefully scale the figure size better.

I'm not sure why the text is missing in your plot?

**Comment by apiszcz** [comment]
I pulled the latest SS from the repo.. Next I made the PR changes to metrictables.py, still same behavior on my end.

**Comment by sdhiscocks** [comment]
What version of _matplotlib_ are you using?
