### ISSUE TITLE
Birth component in the point process tracker

### ISSUE THREAD

**Issue by ekhunter123** [dstl/Stone-Soup#486]
I've been looking at the PointProcessMultiTargetTracker class found[ here](https://stonesoup.readthedocs.io/en/v0.1b6/_modules/stonesoup/tracker/pointprocess.html)  and I have some questions about the birth component parameter. 

In the tracks_gen() generator method, the birth component is added to the Gaussian mixture. As those lines of code are in the for loop, they are done at every time step. Additionally, at every time step the birth component State stays constant (except for changing the timestamp). This means that the same birth component is added to the mixture over and over again. I think this is supposed to reflect a situation where we know that targets keep reappearing at the same point at regular intervals. This seems quite useful and broadens the applications of the tracker! But if this is the intended use (and not a bug), I think it should be explained in the documentation. It might also be nice to give the user an option to pass prior(s) into the tracker. These would be like the birth component except that they would only be added to the Gaussian mixture at the first time step. This would reflect is the user knows where the target object(s) starts. 

It is also worth noting that the Property for the birth_component gives a default None indicating that it is optional. However the code has the line _self.birth_component.timestamp = time_ which causes an error if birth_component is None. So the birth_component is actually not optional even though the documentation says it is. 

Does anyone else have any thoughts about this? Is there something I'm missing? If changes are needed I'm more than happy to create a pull request. Thank you :)

**Comment by sdhiscocks** [comment]
> It is also worth noting that the Property for the birth_component gives a default None indicating that it is optional. However the code has the line _self.birth_component.timestamp = time_ which causes an error if birth_component is None. So the birth_component is actually not optional even though the documentation says it is.

Yeah, this shouldn't be optional (or if it should be optional, need to skip over adding a  birth component.

On your other questions, I think @Campbell101 may be best placed to answer.

**Comment by Campbell101** [comment]
> This means that the same birth component is added to the mixture over and over again. I think this is supposed to reflect a situation where we know that targets keep reappearing at the same point at regular intervals.

In these point process type filters (PHD & LCC), this birth Gaussian component covers the entire state space (or it should as long as the initial state/covariance has been set up correctly) with a weight that is expected number of births per timestep. This means that in the update step when the data association / hypothesiser step takes place, the birth component should get associated with all measurements obtained, allowing for new targets to be created. 

> This seems quite useful and broadens the applications of the tracker!

This is an designed feature of these types of filters!

> It might also be nice to give the user an option to pass prior(s) into the tracker. These would be like the birth component except that they would only be added to the Gaussian mixture at the first time step. This would reflect is the user knows where the target object(s) starts.

Yes, you could add an initial birth component/s with lower covariance around the area where you expect targets to be. You could also use a "measurement-driven birth" model instead: http://ba-ngu.vo-au.com/vo/RCVV_SMCPHD12.pdf

For more info about the GM implementation of these kinds of filter see https://ieeexplore.ieee.org/document/1710358 and https://ieeexplore.ieee.org/document/4086095

**Comment by ekhunter123** [comment]
> In these point process type filters (PHD & LCC), this birth Gaussian component covers the entire state space (or it should as long as the initial state/covariance has been set up correctly) with a weight that is expected number of births per timestep. 

Ok I see! I didn't realize that it's state vector and covariance had to cover the entire state space. If I understand correctly, this birth component will raise the distribution in the state space above 0. That way the hypothesiser will give a non-zero probability that the measurement pertains to a target. So the birth component is more like a base for the rest of the Gaussian mixture, rather than representing a single target? 

Once the filter has gone through a couple time steps and has some Gaussian components for the targets, what is the effect of the birth component addition? I guess if the rest of the tracks die off then it would not be able to create new ones without the birth component.  

Thank you for clarifying this! I really appreciate it.
