### ISSUE TITLE
Euclidean distance metric for polar coordinates

### ISSUE THREAD

**Issue by ekhunter123** [dstl/Stone-Soup#524]
I noticed that in situations where polar/spherical coordinates are used for detections (like RadarBearingRange or RadarElevationBearingRange), the DistanceHypothesiser was returning weird distances. I believe it is because the measures used from measures.py don't convert the [Bearing, Range] coordinates to Cartesian. The DistanceHypothesiser doesn't convert them either before passing them into the measure. I ran a few test cases to confirm this problem. 

For example, if there is a detection at [Bearing(1.0), 20] and the prediction is at [Bearing(1.2), 25], then the Euclidean measure will simply return sqrt{(1.2-1.0)^2 + (25-20)^2}. This is clearly not correct. 

This isn't a big problem in the single target case when there is no clutter, though it will have an impact. I only noticed it because I am trying to add a ClutterModel for the radar measurements, so there were multiple measurements being checked.

I think the easiest way to fix it would be to add an if statement in the DistanceHypothesiser to check if the coordinates are already Cartesian or not. Alternatively, the change could be made in measures.py, in which case it would have to be done for each measure type (ie Euclidean, Mahalanobis...). But that would make it more extensible if there are other uses for the measures. This is probably the better way to fix it. I don't mind writing a fix but I want to check that I am not misunderstanding the code before doing so. Does someone see something I am missing? Thank you!

**Comment by gawebb-dstl** [comment]
You can't always completely convert from measurement space to cartesian space, for example in the Cartesian2DToBearing & CartesianToElevationBearing models. In these examples the DistanceHypothesiser has to calculate the 'distance' in measurement space (polar). So as a default you have measure the distance in the measurement state space.

However for RadarBearingRange or RadarElevationBearingRange the Euclean distance in measurement space (polar) (in most instances) will be dominated by the range component.  

For example, if you're comparing your prediction of [Bearing(1.0), 20,000] against two measurements of A, [Bearing(1.0), 21,000] and B, [Bearing(1.5), 20,000]. In cartesian A (dist=1,000) is much closer than B (dist=~10,000). However in polar measurement space B (dist=0.5) is much closer than A (dist=1,000). 

This is problem is taking the Euclean distance in polar space. A new Measure could be made to account for this.  However I don't think theis problem affects the Mahalanobis & SquaredGaussianHellinger distance as they take into account the covariance of a state which would have a much larger covariance in the range component that

**Comment by ekhunter123** [comment]
Ok, I will try using the Mahalanobis or some other measure. Thanks for explaining. 

What do you mean by "You can't always completely convert from measurement space to cartesian space"? Could the DistanceHypothesiser convert the measurements to cartesian before calling the distance? Thanks

**Comment by ekhunter123** [comment]
Ah I see, thanks for such a detailed response!
