### ISSUE TITLE
Track metadatas lead to huge memory consumption over time

### ISSUE THREAD

**Issue by sglvladi** [dstl/Stone-Soup#540]
When applying a tracker to a large scale dataset with plenty of metadata, the ``metadatas`` property of ``Tracks`` grows uncontrollably and ends up dominating the consumed memory. As an example, processing 24-hours worth of AIS data from Europe and the North Atlantic region manages to crash a system with 128GB of RAM!!

The existing ``StatesLengthLimiter`` is a handy tool for limiting the length of maintained ``states`` history for ``Tracks``, however it does not impose any restrictions to the ``metadatas`` property. It would therefore be useful if we could implement an equivalent class that limits the length of the ``metadatas``, so as to avoid memory bottlenecks.

**Comment by oharrald-Dstl** [comment]
Perhaps we store metadata delta instead of a brand new metadata with each new appended state to a track?
