### ISSUE TITLE
Radar cluttertest doesn't consider no clutter

### ISSUE THREAD

**Issue by oharrald-Dstl** [dstl/Stone-Soup#575]
On occasion, the radar clutter test raises an error due to no clutter being generated leading to len(detections) == 1.
See:
https://github.com/dstl/Stone-Soup/blob/31b5ff296dee2eff5732dd6fe6804c8d12384010/stonesoup/sensor/radar/tests/test_radar.py#L675

**Comment by ekhunter123** [comment]
Good point! A quick fix could be to increase the clutter rate in the test. But since it is Poisson distributed, there could still be no clutter (but it would happen more rarely). What if I added an attribute to the clutter model that would be True if it generated clutter at the current time step, and False if it didn't? I'm thinking before line 72 in [clutter.py](https://github.com/dstl/Stone-Soup/blob/31b5ff296dee2eff5732dd6fe6804c8d12384010/stonesoup/models/clutter/clutter.py). Then the test could use that attribute to adjust the assertion. Is that overkill?

**Comment by sdhiscocks** [comment]
A fix seed could also be used? Or the test could loop over measure, say 3 times, appending measurements, and check that number of measurements is greater than 3.

**Comment by sdhiscocks** [comment]
Actually, looking at the clutter model, it may be worth adding an option for a seed to be set, such that runs in general can be reproduced. Can then use this to get reproducible test as well.

Example here with Gaussian Models: https://github.com/dstl/Stone-Soup/blob/31b5ff296dee2eff5732dd6fe6804c8d12384010/stonesoup/models/base.py#L207-L215

Or in simulator: https://github.com/dstl/Stone-Soup/blob/31b5ff296dee2eff5732dd6fe6804c8d12384010/stonesoup/simulator/simple.py#L93-L98 https://github.com/dstl/Stone-Soup/blob/31b5ff296dee2eff5732dd6fe6804c8d12384010/stonesoup/simulator/simple.py#L122-L124

(Side note: I think line 98 in sim should be same as 215. Might be bug there)

**Comment by ekhunter123** [comment]
That is a good idea! I will work on that.

I agree with your side note. If the seed is None, that might cause a problem on line 98.

**Comment by ekhunter123** [comment]
I started implementing this change. I made a seed parameter and a RandomState object. 
`
    seed: Optional[int] = Property(
        default=None,
        doc="Seed for random number generation")     
`

    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)
        self.random_state = np.random.RandomState(self.seed)`

We can use `self.random_state.poisson()` to randomly determine how many clutter points to create. But I'm not sure how to make it work when we call the `distribution` function parameter. This function gets passed in by the user and is responsible for actually generating the random points where clutter will be. Do you know how to make the RandomState object call a function where all we have is a pointer to the function? We could just set a numpy seed, but the documentation says to try to avoid that and use RandomStates instead. I'm a little stuck on how to do this.
Here is the line where we call `self.distribution`
https://github.com/dstl/Stone-Soup/blob/31b5ff296dee2eff5732dd6fe6804c8d12384010/stonesoup/models/clutter/clutter.py

**Comment by sdhiscocks** [comment]
> I'm not sure how to make it work when we call the `distribution` function parameter. This function gets passed in by the user and is responsible for actually generating the random points where clutter will be. Do you know how to make the RandomState object call a function where all we have is a pointer to the function? We could just set a numpy seed, but the documentation says to try to avoid that and use RandomStates instead. I'm a little stuck on how to do this. For reference, we call `self.distribution` on line 73 https://github.com/dstl/Stone-Soup/blob/main/stonesoup/models/clutter/clutter.py

I guess it's possible to pass something like `np.random.RandomState(self.seed).uniform` for the `distribution` if there is need for a fixed seed?
