### ISSUE TITLE
Record metadata as part of Track

### ISSUE THREAD

**Issue by dlast-dstl** [dstl/Stone-Soup#59]
Record metadata (especially changes in metadata) as part of the Track. Example: what MMSI (ship-unique identifier) the ship is broadcasting at each detection.

**Comment by sglvladi** [comment]
@sdhiscocks can this be closed?

**Comment by sdhiscocks** [comment]
> @sdhiscocks can this be closed?

Yes, I think so, as now you can add custom track only metadata since changes in #121.
