### ISSUE TITLE
JPDA in Tutorial 9 does not work

### ISSUE THREAD

**Issue by adielstatman** [dstl/Stone-Soup#639]
Hi. 
modifying Lines 125-130 of Tutorial 9 to: 

> from stonesoup.hypothesiser.probability import PDAHypothesiser
> hypothesiser = PDAHypothesiser(predictor, updater, clutter_spatial_density=0.1)
> from stonesoup.dataassociator.probability import JPDA
> data_associator = JPDA(hypothesiser)

outputs:

> AttributeError: 'MultipleHypothesis' object has no attribute 'prediction'

What else should I do in order to operate the JPDA there?
Thanks,
Adiel.

**Comment by sdhiscocks** [comment]
You'll need to replace the `MultiTargetTracker` with the [`MultiTargetMixtureTracker`](https://stonesoup.readthedocs.io/en/v0.1b9/stonesoup.tracker.html#stonesoup.tracker.simple.MultiTargetMixtureTracker).

**Comment by adielstatman** [comment]
Hi.
I don't want to use a "detector" in my class but a pre-defined "all_measurements" set.
Thus I have modified MultiTargetMixtureTracker the following. Note it is not inherit from Tracker.

> class MultiTargetMixtureTracker1:
> 
>  
> 
>     def __init__(self, initiator,deleter,data_associator,updater,all_measurements,start_time): 
> 
>         self.initiator=initiator
> 
>         self.deleter=deleter
> 
>         self.data_associator=data_associator
> 
>         self.updater=updater
> 
>         self.all_measurements=all_measurements
> 
>         self.start_time=start_time
> 
>        
> 
>        # super().__init__( *args)
> 
>  
> 
> 
>     def tracks_gen(self):
> 
>         tracks = set()
> 
>  
> 
>         for n, detections in enumerate(self.all_measurements):
> 
>             time=self.start_time+timedelta(seconds=n)
> 
>  
> 
>             associations = self.data_associator.associate(
> 
>                 tracks, detections, time)
> 
>             unassociated_detections = set(detections)
> 
>             for track, multihypothesis in associations.items():
> 
>  
> 
>                 # calculate each Track's state as a Gaussian Mixture of
> 
>                 # its possible associations with each detection, then
> 
>                 # reduce the Mixture to a single Gaussian State
> 
>                 posterior_states = []
> 
>                 posterior_state_weights = []
> 
>                 for hypothesis in multihypothesis:
> 
>                     if not hypothesis:
> 
>                         posterior_states.append(hypothesis.prediction)
> 
>                     else:
> 
>                         posterior_states.append(
> 
>                             self.updater.update(hypothesis))
> 
>                     posterior_state_weights.append(
> 
>                         hypothesis.probability)
> 
>  
> 
>                 means = StateVectors([state.state_vector for state in posterior_states])
> 
>                 covars = np.stack([state.covar for state in posterior_states], axis=2)
> 
>                 weights = np.asarray(posterior_state_weights)
> 
>  
> 
>                 post_mean, post_covar = gm_reduce_single(means, covars, weights)
> 
>  
> 
>                 missed_detection_weight = next(hyp.weight for hyp in multihypothesis if not hyp)
> 
>  
> 
>                 # Check if at least one reasonable measurement...
> 
>                 if any(hypothesis.weight > missed_detection_weight
> 
>                        for hypothesis in multihypothesis):
> 
>                     # ...and if so use update type
> 
>                     track.append(GaussianStateUpdate(
> 
>                         post_mean, post_covar,
> 
>                         multihypothesis,
> 
>                         multihypothesis[0].measurement.timestamp))
> 
>                 else:
> 
>                     # ...and if not, treat as a prediction
> 
>                     track.append(GaussianStatePrediction(
> 
>                         post_mean, post_covar,
> 
>                         multihypothesis[0].prediction.timestamp))
> 
>  
> 
>                 for hyp in multihypothesis:
> 
>                     if hyp.weight > missed_detection_weight:
> 
>                         if hyp.measurement in unassociated_detections:
> 
>                             unassociated_detections.remove(hyp.measurement)
> 
>             tracks -= self.deleter.delete_tracks(tracks)
> 
>             tracks |= self.initiator.initiate(unassociated_detections, time)
> 
>  
> 
>         return tracks

running this with "all measurements" of Tutorial 9, yields the the following error:

> MultipleHypothesis`` object has no attribute 'prediction' 

(prediction which the updater needs)
What am I do wrong?
