### ISSUE TITLE
code for performance analysis 

### ISSUE THREAD

**Issue by adielstatman** [dstl/Stone-Soup#647]
Hi.
Following an analysis such as Tutorial 9 or 10, I want to show the distance between the 
-tracks and the GT
-Detections and GT
-tracks and Detections 
in each time.
Is there some general code for such performance analysis?
Thanks.

**Comment by sdhiscocks** [comment]
Have you seen the [Metrics example](https://stonesoup.readthedocs.io/en/v0.1b9/auto_examples/Metrics.html#sphx-glr-auto-examples-metrics-py)? That has some metrics for track to ground truth comparison. There aren't any metrics for comparing with detections currently.
