### ISSUE TITLE
Verify NMEA reader

### ISSUE THREAD

**Issue by mamoonrashid** [dstl/Stone-Soup#65]
A branch called "nmea" has been added. This branch contains a class called NMEAReader, which is located in "reader/nmea.py" file.  Additionally, this branch also contains facilities (decoder, parser, definitions, etc) to parse raw AIS messages in NMEA format. These facilities are all under "reader/aisutils" directory. There are several issues that need to be addressed:

1. The facilities added to parse raw AIS messages do add some complexity to StoneSoup, which might be outside the scope of the project. However, to my knowledge there are no reliable AIS parsing libraries in pure Python (the most popular one on pip requires a C++ compiler, which is not so straightforward to get and install on Windows).  So, do we keep the code under "reader/aisutils" as part of StoneSoup? Or do we release aisutils as a separate open-source library and add that as a requirement for StoneSoup?

2. At the moment, NMEAReader class only reads AIS message types 1, 2, and 3, which are all Class A vessel position reports. Do we need to read any other types?

3. I noticed that OpenSkyReader outputs detections in time ascending manner. Not sure if this because the source (OpenSky) provides detections in this manner, or the reader is designed to output detections in time sorted manner. Currently, the detections generated by the NMEAReader class are not guaranteed to be sorted because the raw AIS feed is not necessarily sorted in time. This means that the output of detections_gen can potentially look something like this: 
       i. 1516233686, Detections Set A
      ii. 1516233696, Detections Set B
     iii. 1516233686, Detections Set C

The time value of output i. and output iii. above is same (1516233686), but the Detection sets are different. Is this okay? My guess is probably not, but I'm not sure how to fix this at the moment.

**Comment by sdhiscocks** [comment]
Decide to be separate project
