### ISSUE TITLE
Kalman filter not working with 3D groundtruth

### ISSUE THREAD

**Issue by ColeBromfield01** [dstl/Stone-Soup#845]
[kalman_3d.txt](https://github.com/dstl/Stone-Soup/files/12430559/kalman_3d.txt)
[points2.csv](https://github.com/dstl/Stone-Soup/files/12430560/points2.csv)

I'm trying to create a ground truth and measurements with the points in the csv file, and then perform a Kalman filter calculation, but the track ends up blown up every time (see image--track goes way beyond the groundtruth and points)
![track](https://github.com/dstl/Stone-Soup/assets/143104236/4683ddb7-b98b-43aa-b3af-4dfdc4f80eb9)

How might I fix this issue?

**Comment by ColeBromfield01** [comment]
Thank you for the response!  Where in the code do I change the location of the sensor?  Sorry, I am still somewhat new to StoneSoup

**Comment by jswright-dstl** [comment]
In your kalman_3d.txt file, you set the sensor location as the following:

sensor_x = 0
sensor_y = 0
sensor_z = 50

**Comment by ColeBromfield01** [comment]
Is there a specific method for figuring out the best initial coordinates to use?  I've tried a few and some have made the uncertainty slightly better but still very high

**Comment by ColeBromfield01** [comment]
I think I've improved it by changing the sensor position and changing the covar matrix to CovarianceMatrix(np.array(np.diag([np.deg2rad(0.05)**2, np.deg2rad(0.05)**2, 100]))), but I'm still getting some weird points (
![track2](https://github.com/dstl/Stone-Soup/assets/143104236/0fe9c6a0-bdf7-4877-ba3f-dbdc28661099)
) and a warning about complex values (ComplexWarning: Casting complex values to real discards the imaginary part
  return np.asarray(x, float)),  Do you know what could be causing that?

I really appreciate all of your help

**Comment by hpritchett-dstl** [comment]
Hi @ColeBromfield01,

In your dataset there is a lot of "jumping" around by the target, which a constant velocity model doesn't accurately capture. You can see this happening between line 11 and 12 in your data.

Are there multiple "targets" in this scenario, or is it a single target problem?

**Comment by ColeBromfield01** [comment]
This is a single target, and it's supposed to be moving in circles.  Is there a better transition model to use?

Also is there a way to affect the balance of whether the measured or predicted value is taken more into account in the Kalman calculation?
