### ISSUE TITLE
transition_model lacks "matrix" attribute - jacobian?

### ISSUE THREAD

**Issue by Orchidaceae** [dstl/Stone-Soup#853]
I encountered an issue when following the [Introduction guide to Kalman filter](https://stonesoup.readthedocs.io/en/v1.1/auto_tutorials/01_KalmanFilterTutorial.html#sphx-glr-auto-tutorials-01-kalmanfiltertutorial-py). The transition_model referenced on Line [72](https://github.com/dstl/Stone-Soup/blob/f24090cc919b3b590b84f965a3884ed1293d181d/stonesoup/predictor/kalman.py#L72) and [92](https://github.com/dstl/Stone-Soup/blob/f24090cc919b3b590b84f965a3884ed1293d181d/stonesoup/predictor/kalman.py#L92C11-L92C11) in kalman.py does not have a matrix attribute. In this case I believe that the referenced ```CombinedGaussianTransitionModel``` do have a jacobian attribute to be used instead, like this:
```
# line 72
return self.transition_model.jacobian(state=kwargs['prior'], **kwargs)

# line 92
return self.transition_model.jacobian(state=prior, **kwargs) @ prior.state_vector
```
With these changes the example runs just fine, I am however not sure if it will work for other transition models.

**Comment by jswright-dstl** [comment]
The Kalman filter tutorial uses the `CombinedLinearGaussianTransitionModel` which takes linear Gaussian transition models that all have the `.matrix` attribute. 
The `CombinedGaussianTransitionModel` is slightly different, the assumption is that the transition models used here are Gaussian, i.e., not linear (and no `matrix` attribute) and require the use of the `.jacobian` attribute.
