### ISSUE TITLE
GOSPA does not return the correct associations

### ISSUE THREAD

**Issue by Carlson-J** [dstl/Stone-Soup#897]
When we compute the GOSPA metrics and the truth to measurement associations, we are not giving the correct assignments.

https://github.com/dstl/Stone-Soup/blob/71b47f9c19bfdbc225d659b34277502052b4e4e0/stonesoup/metricgenerator/ospametric.py#L279

When measurements are outside the maximum association distance, we correctly add the max cost and update the missed/false terms, but we keep the association. I think we should also make the truth_to_measurement assignment -1 (the unassigned value) as well. 

I'm planning on changing it when I add the switching term, see https://github.com/dstl/Stone-Soup/discussions/876, where this mappin g will be used to update the switching term.

**Comment by sdhiscocks** [comment]
Fixed in #898
