### ISSUE TITLE
AnimatedPlotterly doesn't accept a mix of offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by orosoman-dstl** [dstl/Stone-Soup#908]
Title. Doing this will lead to a `TypeError` when Stone Soup tries to do arithmetic using the datetimes. This can be fixed in a couple of lines by converting using the `tzinfo` property, maybe giving a warning if that's necessary?

**Comment by sdhiscocks** [comment]
So this issue will be caused with the input data. If all data that is read into Stone Soup objects is TZ aware, this shouldn't be an issue. Having mix of both will cause issues in a number of places, not just with plotter.

**Comment by orosoman-dstl** [comment]
OK, fair enough.
