### ISSUE TITLE
Addition of Angle types breaks UKF functions

### ISSUE THREAD

**Issue by sglvladi** [dstl/Stone-Soup#92]
When UKF related functions, or more generally functions that perform matrix multiplication, (e.g `sigma2gauss`) are called on matrices of `StateVector` objects that contain an `Angle` type, the following error is experienced:

```

~\Anaconda3\lib\site-packages\stonesoup\functions.py in sigma2gauss(sigma_points, mean_weights, covar_weights, covar_noise)
    157     """
    158 
--> 159     mean = sigma_points@mean_weights[:, np.newaxis]
    160 
    161     points_diff = sigma_points - mean

TypeError: ufunc 'matmul' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

This is an issue identified by @sdhiscocks and myself during the Nelson Codeathon. A quickfix was applied by casting all occurrences of `StateVector` objects to `np.float`, e.g.:

```python
mean = sigma_points.astype(np.float_)@mean_weights[:, np.newaxis]
```

However, the above comes at the cost of losing the benefits (e.g. angle-wrapping) provided by the `Angle` classes. 

A suggested alternative was to cast such `StateVector` matrices to `CovarianceMatrix` objects before multiplying, however this was not feasible at the time due to cyclic import errors (potentially to be solved by #91).

**Comment by sdhiscocks** [comment]
@sglvladi: Could you confirm if this is resolved?

**Comment by sglvladi** [comment]
@sdhiscocks I can confirm it was fixed with the old UKF implementation, but haven't really tested it after #110 was merged. I doubt that it should make any difference, but I'll test it out and will come back with an answer shortly.

**Comment by DaveKirkland** [comment]
@sdhiscocks I'd would say close this issue and then raise another one if necessary.
