### ISSUE TITLE
ImportError 

### ISSUE THREAD

**Issue by avcuenes** [dstl/Stone-Soup#935]
I run 08_JPDATutorial.py but I got the following error;

File "08_JPDATutorial.py", line 104, in <module>
    from stonesoup.plotter import AnimatedPlotterly
ImportError: cannot import name 'AnimatedPlotterly'

**Comment by mharris-dstl** [comment]
This is very likely to be a local issue rather than an issue with the codebase. Do you have Plotly installed? I think this is the most likely reason but may be something else.

**Comment by avcuenes** [comment]
Yes I install Plotly but result is not changed

**Comment by avcuenes** [comment]
I try to install this project by following command ;

git clone "https://github.com/dstl/Stone-Soup.git"
cd Stone-Soup
python -m pip install -e ".[dev]"

I take this error 
Directory '.' is not installable. File 'setup.py' not found.

**Comment by avcuenes** [comment]
@mharris-dstl

**Comment by hpritchett-dstl** [comment]
> I try to install this project by following command ;
> 
> git clone "https://github.com/dstl/Stone-Soup.git" cd Stone-Soup python -m pip install -e ".[dev]"
> 
> I take this error Directory '.' is not installable. File 'setup.py' not found.

Hi @avcuenes, this sounds like it could be an issue with the version of pip you have installed. Try upgrading it to the latest version and try again.

**Comment by avcuenes** [comment]
I found problem ıf you install this project by using pip install stonesoup commad this install just  stonesoup==0.1b7
 version

**Comment by avcuenes** [comment]
I try to install pip install stonesoup==1.1 but gives me following error

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement stonesoup==1.1 (from versions: 0.1b1, 0.1b2, 0.1b3, 0.1b4, 0.1b5, 0.1b6, 0.1b7)
ERROR: No matching distribution found for stonesoup==1.1

**Comment by mharris-dstl** [comment]
@avcuenes has the suggestion by @hpritchett-dstl worked for you? And if not, are you happy using an older version?

**Comment by avcuenes** [comment]
Thanks for your answer. I think problem is about my computer cant install new version of some lib.
