### ISSUE TITLE
Getting predicted measurement with no measurement noise

### ISSUE THREAD

**Issue by narykov** [dstl/Stone-Soup#961]
It would be useful to have an option to exclude measurement noise when computing statistics of the predicted measurement. In particular, we've been interested to use the `predict_measurement` method of `UnscentedKalmanUpdater` when performing measurement linearisation for the IPLF algorithm. However, the [unscented transform](https://github.com/dstl/Stone-Soup/blob/dd617f8457cfedf057aea357ad646124be494225/stonesoup/updater/kalman.py#L397-L400) inside `predict_measurement` always receives noise covariance, whereas it could have worked without it if `covar_noise=None` is used, as enabled by [this](https://github.com/dstl/Stone-Soup/blob/dd617f8457cfedf057aea357ad646124be494225/stonesoup/functions/__init__.py#L217-L218) feature in `sigma2gauss`.

**Comment by sdhiscocks** [comment]
Look like it shouldn't be difficult to add an additional Boolean argument (`noise`/`measurement_noise`/`covar_noise`??) to all the updaters' `predict_measurement` method to support this.
